name: CodeAudits-Action
description: Analyse your project with Google Gemini for the code quality, refactoring, architecture and good practices. 
author: Miroslaw Stanek

branding:
  icon: compass
  color: gray-dark

inputs:
  mode:
    description: 'Operation mode: "parse-repo" for repository parsing or "parse-pr" for Pull Request analysis'
    default: 'parse-repo'
    required: false
  style:
    description: Parsed document style. Use 'markdown', 'xml' or 'plain'
    default: 'markdown'
  compress:
    description: Run intelligent code parsing to reduce tokens (see Repomix documentation for the details)
    default: 'false'
  working-directory:
    description: The directory in which to run the action. Defaults to the repository root.
    default: '.'
    required: false
  llm-prompt:
    description: 'The name of the prompt file for the Gemini prompt (available prompts in README).'
    required: false
  llm-custom-prompt:
    description: 'The name of the custom prompt file from /.codeaudits/prompts directory in the repository.'
    required: false
  gemini-api-key:
    description: 'Gemini API key for AI-powered code analysis'
    required: false
  includeFiles:
    description: 'Space-separated list of files to include in the analysis (e.g., from changed files)'
    required: false
  output:
    description: The filename containing parsed repository
    default: "parsed-repo.txt"
  main-branch-file:
    description: 'Path to the parsed main branch file (for parse-pr mode)'
    required: false
  feature-branch-file:
    description: 'Path to the parsed feature branch file (for parse-pr mode)'
    required: false

# Define your outputs here.
outputs:
  parse-metadata:
    description: Metadata of the parsed repository
  parsed-file-name:
    description: Name of the parsed output file
  submission-status:
    description: Result of the submission to CodeAudits

runs:
  using: docker
  image: Dockerfile
  env:
    GEMINI_API_KEY: ${{ inputs.gemini-api-key }}
