name: CodeAudits-Action
description: Github Action to parse your source code
author: Miroslaw Stanek

branding:
  icon: compass
  color: gray-dark

inputs:
  style:
    description: Parsed document style. Use 'markdown', 'xml' or 'plain'
    default: 'markdown'
  compress:
    description: Run intelligent code parsing to reduce tokens
    default: 'false'
  working-directory:
    description: The directory in which to run the action. Defaults to the repository root.
    default: '.'
    required: false
  llm-instruction:
    description: 'The name of the instruction file for the Gemini prompt (e.g., architecture-refactoring).'
    required: false
  gemini-api-key:
    description: 'The API key for the Gemini API.'
    required: false

# Define your outputs here.
outputs:
  parse-metadata:
    description: Metadata of the parsed repository
  parsed-file-name:
    description: Name of the parsed output file
  submission-status:
    description: Result of the submission to CodeAudits

runs:
  using: docker
  image: Dockerfile
