name: CodeAudits-Action
description: Github Action to parse your project and do AI source analysis with Google Gemini
author: Miroslaw Stanek

branding:
  icon: compass
  color: gray-dark

inputs:
  style:
    description: Parsed document style. Use 'markdown', 'xml' or 'plain'
    default: 'markdown'
  compress:
    description: Run intelligent code parsing to reduce tokens (see Repomix documentation for the details)
    default: 'false'
  working-directory:
    description: The directory in which to run the action. Defaults to the repository root.
    default: '.'
    required: false
  llm-prompt:
    description: 'The name of the prompt file for the Gemini prompt (available prompts in README).'
    required: false
  llm-custom-prompt:
    description: 'The name of the custom prompt file from /.codeaudits/prompts directory in the repository.'
    required: false
  gemini-api-key:
    description: 'Gemini API key for AI-powered code analysis'
    required: false

# Define your outputs here.
outputs:
  parse-metadata:
    description: Metadata of the parsed repository
  parsed-file-name:
    description: Name of the parsed output file
  submission-status:
    description: Result of the submission to CodeAudits

runs:
  using: docker
  image: Dockerfile
  env:
    GEMINI_API_KEY: ${{ inputs.gemini-api-key }}
