name: Parse and submit - this codebase, custom prompt

on:
  workflow_dispatch:

jobs:
  parse-repository:
    runs-on: ubuntu-latest
    name: Parse this repository for CodeAudits
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse and Submit Repository
        uses: frogermcs/codeaudits-parse@v2.0.0
        id: parse
        with:
          style: markdown
          compress: false
          llm-custom-prompt: simplification-prompts
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
      
      - name: Upload Prompt File as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: parsed-repo.txt
          path: parsed-repo.txt
