name: /TEST/ Parse and submit - this codebase

on:
  workflow_dispatch:

jobs:
  parse-repository:
    runs-on: ubuntu-latest
    name: Parse this repository for CodeAudits
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch more history for changed files detection
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          # Get all changed files in the current branch compared to main
          base_sha: 'origin/main'

      - name: List all changed files
        run: |
          echo "Changed files:"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "  - $file"
          done
          
          echo ""
          echo "Total changed files: ${{ steps.changed-files.outputs.all_changed_files_count }}"

      - name: Parse and SubmitRepository
        uses: ./
        id: parse
        with:
          style: markdown
          compress: false
          llm-prompt: architecture-refactoring
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
          includeFiles: ${{ steps.changed-files.outputs.all_changed_files }}
      
      - name: Upload Prompt File as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: parsed-repo.txt
          path: parsed-repo.txt
