name: /TEST/ Parse and submit - external codebase

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'Repo URL for audit'
        default: 'https://github.com/frogermcs/codebase-dump'
        required: true
        type: string

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract repo name from URL
        id: extract_repo_name
        run: |
          REPO_URL="${{ github.event.inputs.repo_url }}"
          REPO_NAME=$(basename "$REPO_URL" .git)
          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT

      - name: Clone target repository with gh
        run: gh repo clone ${{ github.event.inputs.repo_url }} ${{ steps.extract_repo_name.outputs.repo_name }} -- --depth 1
        env:
          GH_TOKEN: ${{ secrets.GH_CLONE_PRIV_REPOS }}

      - name: Run CodeAudits Action
        uses: ./  # Assuming your action is in the root of the repository
        with:
          style: markdown
          llm-prompt: architecture-refactoring
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
          working-directory: ${{ steps.extract_repo_name.outputs.repo_name }} # Set the working directory

      - name: Upload parsed file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: parsed-repo
          path: parsed-repo.txt